"""E 系列多产品生态 · 跨产品契约对象字段白名单（E-1 合同冻结）。

本模块只做一件事：把文档 17 §3 冻结的 4 个跨产品契约对象字段白名单，以及
sanitize 纯函数固定为机器可校验口径。供 E-2~E-9 各步比对、各产品落地时复用。

E-1 阶段红线（本模块严格遵守）：
- 只含字段白名单常量 + sanitize 纯函数，零业务逻辑。
- 不 import 任何产品能力包，也不 import 检索/rerank/retrieval/summary 等内核运行时。
- 不被任何现有端点接线，不改变任何运行时行为。
- 白名单内不得出现任何正文型字段（raw_case/raw_query/full_text/content/chunk_text/...）。
  sanitize 主动丢弃非白名单键，并显式拒绝正文型键。

E4-1 追加：intake 案情录入端入口合同（冻结口径，纯数据 + 纯函数，不接线）。
E4-2 追加：intake 脱敏纯函数（本地脱敏 + 要素抽取 + 后端防御层，不接线）。
E5-1 追加：法条检索 StatuteRef 契约对象（第 5 个跨产品契约对象，纯数据 + 纯函数，不接线）。
E6-1 追加：文书工作台 DraftDescriptor 契约对象（第 3 契约对象，合同变更追加 statute_refs，不接线）。
"""
from __future__ import annotations

from .whitelist import (
    CANDIDATE_REF_FIELDS,
    CASE_FOLDER_FIELDS,
    CONTRACT_FIELD_WHITELIST,
    DRAFT_DESCRIPTOR_FIELDS,
    FORBIDDEN_BODY_KEYS,
    SEARCH_PROFILE_FIELDS,
    ContractViolationError,
    is_forbidden_body_key,
    sanitize_contract,
)
from .intake_contract import (
    INTAKE_CANDIDATE_REF_FIELDS,
    INTAKE_CONSUMES_CONTRACT,
    INTAKE_FORBIDDEN_PII_KEYS,
    INTAKE_PRODUCES_CONTRACT,
    INTAKE_SEARCH_PROFILE_FIELDS,
    assert_no_raw_case_payload,
    is_forbidden_pii_key,
    is_intake_rejected_key,
    sanitize_intake_search_profile,
)
from .intake_sanitize import (
    PLACEHOLDER_ADDRESS,
    PLACEHOLDER_BANK_CARD,
    PLACEHOLDER_EMAIL,
    PLACEHOLDER_ID_CARD,
    PLACEHOLDER_NAME,
    PLACEHOLDER_PHONE,
    PLACEHOLDER_PLATE,
    PLACEHOLDER_USCC,
    QUERY_TEXT_MAX_LEN,
    build_search_profile_from_raw,
    extract_case_cause,
    extract_dispute_focus_keywords,
    extract_region,
    extract_trial_level_preference,
    redact_pii,
    sanitize_intake_profile_payload,
)
from .statute_contract import (
    STATUTE_ANCHOR_FIELDS,
    STATUTE_FORBIDDEN_DISPLAY_KEYS,
    STATUTE_FORBIDDEN_GENERATED_KEYS,
    STATUTE_PRODUCES_CONTRACT,
    STATUTE_REF_FIELDS,
    STATUTE_RELATES_CONTRACT,
    StatuteAnchorRef,
    StatuteRef,
    StatuteRelatedCaseRef,
    assert_statute_anchored,
    is_forbidden_generated_statute_key,
    is_statute_rejected_key,
    is_valid_statute_anchor,
    sanitize_statute_ref,
)
from .drafting_contract import (
    DRAFT_DESCRIPTOR_CORE_FIELDS,
    DRAFT_DESCRIPTOR_E6_FIELDS,
    DRAFT_FORBIDDEN_BODY_KEYS,
    DRAFT_FORBIDDEN_JUDGMENT_KEYS,
    DRAFT_FORBIDDEN_OUTCOME_KEYS,
    DRAFTING_CONSUMES_CONTRACTS,
    DRAFTING_PRODUCES_CONTRACT,
    NOTE_MAX_LEN,
    STRUCTURE_SKELETON_ITEM_MAX_LEN,
    STRUCTURE_SKELETON_MAX_ITEMS,
    TAG_MAX_LEN,
    DraftCandidateRef,
    DraftDescriptor,
    assert_no_draft_body,
    is_draft_rejected_key,
    is_forbidden_draft_body_key,
    is_forbidden_outcome_key,
    sanitize_draft_descriptor,
)
from .casebook_contract import (
    CASE_FOLDER_CORE_FIELDS,
    CASE_FOLDER_E7_FIELDS,
    CASEBOOK_AGGREGATES_CONTRACTS,
    CASEBOOK_FORBIDDEN_DRAFT_KEYS,
    CASEBOOK_FORBIDDEN_JUDGMENT_KEYS,
    CASEBOOK_FORBIDDEN_OUTCOME_KEYS,
    CASEBOOK_PRODUCES_CONTRACT,
    DEFAULT_VISIBILITY,
    TITLE_MAX_LEN,
    VALID_VISIBILITY,
    CaseFolder,
    CaseFolderCandidateRef,
    assert_no_case_body,
    is_case_folder_rejected_key,
    is_forbidden_case_body_key,
    is_forbidden_case_outcome_key,
    sanitize_case_folder,
)

__all__ = [
    "SEARCH_PROFILE_FIELDS",
    "CANDIDATE_REF_FIELDS",
    "DRAFT_DESCRIPTOR_FIELDS",
    "CASE_FOLDER_FIELDS",
    "CONTRACT_FIELD_WHITELIST",
    "FORBIDDEN_BODY_KEYS",
    "ContractViolationError",
    "is_forbidden_body_key",
    "sanitize_contract",
    # --- E4-1 intake 入口合同（冻结口径，不接线）---
    "INTAKE_PRODUCES_CONTRACT",
    "INTAKE_CONSUMES_CONTRACT",
    "INTAKE_SEARCH_PROFILE_FIELDS",
    "INTAKE_CANDIDATE_REF_FIELDS",
    "INTAKE_FORBIDDEN_PII_KEYS",
    "is_forbidden_pii_key",
    "is_intake_rejected_key",
    "assert_no_raw_case_payload",
    "sanitize_intake_search_profile",
    # --- E4-2 intake 脱敏纯函数（本地脱敏 + 要素抽取 + 后端防御层，不接线）---
    "PLACEHOLDER_NAME",
    "PLACEHOLDER_ID_CARD",
    "PLACEHOLDER_USCC",
    "PLACEHOLDER_PHONE",
    "PLACEHOLDER_BANK_CARD",
    "PLACEHOLDER_EMAIL",
    "PLACEHOLDER_PLATE",
    "PLACEHOLDER_ADDRESS",
    "QUERY_TEXT_MAX_LEN",
    "redact_pii",
    "extract_case_cause",
    "extract_region",
    "extract_trial_level_preference",
    "extract_dispute_focus_keywords",
    "build_search_profile_from_raw",
    "sanitize_intake_profile_payload",
    # --- E5-1 法条检索 StatuteRef 契约对象（第 5 个跨产品契约对象，不接线）---
    "STATUTE_PRODUCES_CONTRACT",
    "STATUTE_RELATES_CONTRACT",
    "STATUTE_REF_FIELDS",
    "STATUTE_ANCHOR_FIELDS",
    "STATUTE_FORBIDDEN_GENERATED_KEYS",
    "STATUTE_FORBIDDEN_DISPLAY_KEYS",
    "is_forbidden_generated_statute_key",
    "is_statute_rejected_key",
    "is_valid_statute_anchor",
    "StatuteAnchorRef",
    "StatuteRelatedCaseRef",
    "StatuteRef",
    "sanitize_statute_ref",
    "assert_statute_anchored",
    # --- E6-1 文书工作台 DraftDescriptor 契约对象（第 3 契约对象，合同变更追加 statute_refs，不接线）---
    "DRAFTING_PRODUCES_CONTRACT",
    "DRAFTING_CONSUMES_CONTRACTS",
    "DRAFT_DESCRIPTOR_CORE_FIELDS",
    "DRAFT_DESCRIPTOR_E6_FIELDS",
    "DRAFT_FORBIDDEN_BODY_KEYS",
    "DRAFT_FORBIDDEN_JUDGMENT_KEYS",
    "DRAFT_FORBIDDEN_OUTCOME_KEYS",
    "STRUCTURE_SKELETON_ITEM_MAX_LEN",
    "STRUCTURE_SKELETON_MAX_ITEMS",
    "NOTE_MAX_LEN",
    "TAG_MAX_LEN",
    "is_forbidden_draft_body_key",
    "is_forbidden_outcome_key",
    "is_draft_rejected_key",
    "DraftCandidateRef",
    "DraftDescriptor",
    "sanitize_draft_descriptor",
    "assert_no_draft_body",
    # --- E7-1 案件协作工作台 CaseFolder 契约对象（第 4 契约对象，确认口径，不接线）---
    "CASEBOOK_PRODUCES_CONTRACT",
    "CASEBOOK_AGGREGATES_CONTRACTS",
    "CASE_FOLDER_CORE_FIELDS",
    "CASE_FOLDER_E7_FIELDS",
    "CASEBOOK_FORBIDDEN_JUDGMENT_KEYS",
    "CASEBOOK_FORBIDDEN_DRAFT_KEYS",
    "CASEBOOK_FORBIDDEN_OUTCOME_KEYS",
    "TITLE_MAX_LEN",
    "VALID_VISIBILITY",
    "DEFAULT_VISIBILITY",
    "is_forbidden_case_body_key",
    "is_forbidden_case_outcome_key",
    "is_case_folder_rejected_key",
    "CaseFolderCandidateRef",
    "CaseFolder",
    "sanitize_case_folder",
    "assert_no_case_body",
]
