"""Retrieval adapters for Day 1 step 5.3."""
from app.kernel.rag.retrieval.bm25_fallback import (
    BM25_FALLBACK_SOURCE,
    BM25_RELAXED_RECALL_SOURCE,
    BM25FallbackRetriever,
)
from app.kernel.rag.retrieval.chroma_adapter import ChromaCollectionAdapter
from app.kernel.rag.retrieval.merge import merge_case_candidates
from app.kernel.rag.retrieval.embedding import OllamaEmbeddingClient
from app.kernel.rag.retrieval.models import (
    CaseCandidate,
    ChromaProbeResult,
    EmbeddingResult,
    RetrievalConfigMismatchError,
    RetrievalDependencyError,
    RetrievedChunk,
    VectorCandidate,
    VectorRetrievalResult,
)
from app.kernel.rag.retrieval.service import (
    BM25_FALLBACK_USED,
    BM25_FALLBACK_FAILED,
    CHROMA_EMPTY,
    CHROMA_QUERY_FAILED,
    CHROMA_QUERY_TIMEOUT,
    CHROMA_UNAVAILABLE,
    DEFAULT_SOFT_FILTER_WEIGHTS,
    EMBEDDING_MODEL_MISMATCH,
    EMBEDDING_TIMEOUT,
    EMBEDDING_UNAVAILABLE,
    MIN_CANDIDATES_BEFORE_RELAXED_RECALL,
    ORIGINAL_VECTOR_SOURCE,
    ORIGINAL_VECTOR_TOP_K,
    RELAXED_RECALL_TOP_K,
    VARIANT_VECTOR_SOURCE,
    VARIANT_VECTOR_TOP_K,
    SoftFilterWeights,
    VectorRetrievalService,
)

__all__ = [
    "BM25_FALLBACK_SOURCE",
    "BM25_FALLBACK_FAILED",
    "BM25_FALLBACK_USED",
    "BM25_RELAXED_RECALL_SOURCE",
    "BM25FallbackRetriever",
    "CaseCandidate",
    "CHROMA_EMPTY",
    "CHROMA_QUERY_FAILED",
    "CHROMA_QUERY_TIMEOUT",
    "CHROMA_UNAVAILABLE",
    "ChromaCollectionAdapter",
    "ChromaProbeResult",
    "DEFAULT_SOFT_FILTER_WEIGHTS",
    "EMBEDDING_MODEL_MISMATCH",
    "EMBEDDING_TIMEOUT",
    "EMBEDDING_UNAVAILABLE",
    "EmbeddingResult",
    "MIN_CANDIDATES_BEFORE_RELAXED_RECALL",
    "merge_case_candidates",
    "OllamaEmbeddingClient",
    "ORIGINAL_VECTOR_SOURCE",
    "ORIGINAL_VECTOR_TOP_K",
    "RELAXED_RECALL_TOP_K",
    "RetrievalConfigMismatchError",
    "RetrievalDependencyError",
    "RetrievedChunk",
    "SoftFilterWeights",
    "VARIANT_VECTOR_SOURCE",
    "VARIANT_VECTOR_TOP_K",
    "VectorCandidate",
    "VectorRetrievalResult",
    "VectorRetrievalService",
]
